### ISSUE TITLE
may there be a comparision with eigenmath?

### ISSUE THREAD

**Issue by wuyudi** [p-e-w/savage#7]
Here is its manual

https://georgeweigt.github.io/eigenmath.pdf

https://github.com/georgeweigt/eigenmath

It's also very small.

**Comment by Blue-Skyer** [comment]
Hello,
I am doing research in software engineering ethics. In this issue/pull request, wuyudi (https://github.com/wuyudi) fixes a problem or requests the repo feature using/relying on the techniques from the GitHub project (https://github.com/georgeweigt/eigenmath), in which wuyudi is one of the contributors. We would like to highlight this as an unpleasant "self-promotion" (promoting the use of a project without mentioning that wuyudi is associated with the project).
Regards, Blue Skyer.

**Comment by wuyudi** [comment]
Someone seems to leave a commit and then delete it.

> **Hello,
I am doing research in software engineering ethics. In this issue/pull request, wuyudi (https://github.com/wuyudi) fixes a problem or requests the repo feature using/relying on the techniques from the GitHub project (https://github.com/georgeweigt/eigenmath), in which wuyudi is one of the contributors. We would like to highlight this as an unpleasant "self-promotion" (promoting the use of a project without mentioning that wuyudi is associated with the project).
Regards, Someone.**

---

Here is the response.

I did make a commitment to eigenmath, but was merged https://github.com/georgeweigt/eigenmath/commit/2da91cd21e493f6b3864b4bbe9f2ec76cc399c82, then reverted to https://github.com/georgeweigt/eigenmath/commit/173eecd852b9b0681c492802c3f56941d6678264 by the author. So there is no more of my code.

Meanwhile, this was only a GitHub action script. For building on push.

Also, many software will compare themselves with some similar products. Like dust https://github.com/bootandy/dust#alternatives.

But I will pay attention to this next time, thank you for pointing out this.

**Comment by p-e-w** [comment]
IMO, the author of the (now deleted) comment quoted above was way out of line. The last thing the open source world needs is self-appointed sheriffs policing their made-up "ethics" in other people's repositories.

No ethics violation of any kind occurred here. I appreciate @wuyudi pointing out that repository, which was previously unknown to me. It is completely irrelevant whether or not they contributed to that repo in the past. Free software is neither politics nor academia, and what is and isn't acceptable is determined by the community, not by "software engineering ethics researchers".
